### ISSUE TITLE
Entities pop in and out.

### ISSUE THREAD

**Issue by Xrey274** [tr7zw/EntityCulling#3] opened 2021-02-22 13:00 UTC
Entities pop in and out of existance, which can look very jarring.

https://user-images.githubusercontent.com/30723811/108711883-a7d2a280-751e-11eb-8fec-933ee5ce5078.mp4

**Comment by tr7zw** [comment] 2021-02-22 13:12
The issue is that the "visual hitbox"(basically the same as the normal hotbox except for I think one entity) that can be made visible with f3+b just isn't correct for a lot of entities like sheep/cows, that's why it is so obvious in this case. In the future I'll try to make it more resistant to edge-cases, and try to make the visual hitbox a bit bigger. Also not from the modpage:

> Drawbacks/Visual issues
> 
> Since the updates are done outside of the main game's logic, it may take a split second for culled things to become visible. Updates are done every ~10ms (on a 60hz screen that's less than one frame ~16ms), so it shouldn't be too noticeable. [...] Also in certain (literal) edge cases, you may be able to see when an entity turns invisible/visible. This is due to the (limited)tracing points of the entity not lining up with the camera. Maybe a future improved implementation can use the hitboxes themselves to achieve a perfect result, but for now "if you want to break it, you can break it".

**Comment by Xrey274** [comment] 2021-02-22 20:23
I don't know much about 3d graphics programming and minecraft's internal code, but couldn't you use the model's bounding box, instead of the hitbox?

**Comment by tr7zw** [comment] 2021-02-23 20:05
You can't really use the model since to somehow know that the model is visible in the final image, it needs to be rendered(defeating the purpose of not rendering it). Basically, this needs more accurate entity view boxes, and probably a better tracing implementation that can handle more tricky block setups(using a cone that tries to reach the hitbox while not doublechecking positions and going one "ray" at a time?).

**Comment by NebelNidas** [comment] 2021-03-01 09:36
The same issue happens with paintings, and here it is even more jarring:
https://user-images.githubusercontent.com/48808497/109478596-bf0f1400-7a79-11eb-823d-1c9717363af0.mp4

**Comment by tr7zw** [comment] 2021-03-01 09:44
This might be an issue with paintings having a completely invalid hitbox, and/or the current tracing having a bias in certain +/- directions. I started on hitbox-based tracing yesterday that should hopefully make popins a thing of the past, but I need to put more time into it to get the performance right. Might have dev builds later today that have the working algorithm with the "perfect" tracing, but not at all perfect performance(but I guess still more than usable for "normal" use-cases).

**Comment by NebelNidas** [comment] 2021-03-04 13:55
It seems to work just perfectly now with the new update! Thanks! 😁

**Comment by tr7zw** [comment] 2021-03-04 13:56
Awesome(was hell to get working right too xD). I'll keep this issue open for a bit to see if more issues creep up, but I think that should be it.

**Comment by NebelNidas** [comment] 2021-03-05 09:47
Sorry for having to annoy you again, but I think I found a bug with especially 1x2 holes and large paintings behind it (smaller paintings work fine): 

https://user-images.githubusercontent.com/48808497/110097984-f5ad9d00-7d9f-11eb-888f-05771300ec02.mp4

**Comment by tr7zw** [comment] 2021-03-05 10:39
Is that with the newest version(1.0.3)? Because I did a quick check, and the hitbox of paintings at least looked correct? But maybe they have an issue with giving the correct visual hitbox?

**Comment by tr7zw** [comment] 2021-03-05 18:41
![grafik](https://user-images.githubusercontent.com/5133936/110159218-b5274100-7dea-11eb-969a-ec12514eb650.png)

Huh there is in fact something wrong(should be all around the itemframe, not only the corners. I think it might be an issue because it's only 1 thick.

**Comment by tr7zw** [comment] 2021-03-15 09:16
I think this is fixed in the newest Fabric version on Curse. @NebelNidas can you confirm?

**Closed as completed** 2021-03-20 10:54 UTC

**Comment by NebelNidas** [comment] 2021-04-11 11:30
Sorry for the late response. Yes, I can confirm that it works now! 👍
